### ISSUE TITLE
[ 翻訳の更新 ] :  Mutationページの更新に対応する

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#102]
## 概要

https://github.com/uttk/swr-site/commit/e1411dd847159f70a87ea72eabd5166d3b594177

上記の更新に対応する。

**Comment by uttk** [comment]
@shioyang 

こちらのIssue、対応してもらってもいいですか？
校正の方は私が行います。( 量が少ないので、要らないかもしれませんが。 )

**Comment by shioyang** [comment]
了解です！
