### ISSUE TITLE
[ 校正 ] : "Custom Cache" ページの更新に伴う校正

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#110]
## 概要

#109 の翻訳を校正する。

**Comment by uttk** [comment]
校正者募集中です！
貢献して下さる方は、このIssueにコメントして #111 のreviewに参加して下さい。

**Comment by uttk** [comment]
@shioyang 

すいません。こちらのIssue、対応してもらえませんか？

**Comment by shioyang** [comment]
はーい、わかりました！
