### ISSUE TITLE
[ 校正 ] : Error Handlingページを校正する 

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#19]
## 概要

https://swr.vercel.app/docs/error-handling

上記のページを日本語訳したモノを校正します。

## 担当者

- 無し

**Comment by uttk** [comment]
校正者募集中です！
貢献して下さる方は、このIssueにコメントして #69 のreviewに参加して下さい。

**Comment by shioyang** [comment]
こちらの校正を担当します。
