### ISSUE TITLE
参加表明🙋‍♀️🙋‍♂️

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#3]
## 概要

翻訳活動の参加表明をするためのissueです。
参加される際は、以下のようにして表明してください。

※ ページを指定する際は、既に指定されているページとは被らないようにお願いします🙏
※ 特にページの指定などが無い場合は、その事を明記して下さい。その場合、こちらでページを割り振る事があります。予めご了承ください💁‍♂️💁‍♀️

**翻訳の場合**

```
この翻訳プロジェクトに参加したい xxx です。○○のページの翻訳がしたいです。

## ○○のページ

- [ ここに翻訳したいページのリンク ]( リンク )
```

**校正の場合**

```
この翻訳プロジェクトに参加したい xxx です。○○のページの校正がしたいです。

## ○○のページ

- [ ここに校正したいページのリンク ]( リンク )
```

## 注意事項

現在( 2021/04/05 )、環境構築が整ってないので、それが整い次第このissueへ参加表明して頂いた方へメンションさせて頂きます。予めご了承ください🙏

また、環境構築について知見や意見をお持ちの方は、以下のissueへの参加をお願いします🙇‍♂️🙇‍♀️

https://github.com/uttk/swr-site/issues/2

宜しくお願い致します🤝

**Comment by shioyang** [comment]
この翻訳プロジェクトに参加したい @shioyang です。

特にどのページを翻訳したいというのはないです。
翻訳されたところから順次公開していく形であれば、よく読まれそうなところから翻訳していけると良いのではないかと考えています。
各ページそれほど分量がないので、進捗が良ければ出そろったところで公開でも問題ない気もします。

**Comment by uttk** [comment]
@shioyang 

まだ対応出来てない所などありますが、ドキュメントなどを参考に翻訳を開始しても大丈夫です👌

また、作業を円滑にするためにコラボレーターとして招待しました。
forkリポジトリを作らなくても、このリポジトリに直接Pull Requestを作成して貰って大丈夫ですので、お気軽に貢献して頂けたらと思います。

何か質問などありましたら、Issueを立てるなどしてくれるとありがたいです。

よろしくお願いします🙇‍♂️
