### ISSUE TITLE
PRのマージ方法を考える

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#5]
## 概要

Pull Requestのマージ方法を考える。

## 参考

- [GitHubのMerge、Squash and Merge、Rebase and Mergeを理解する | NHN Cloud Meetup](https://meetup-jp.toast.com/439)

**Comment by shioyang** [comment]
Squash and merge で入れていくのがよいと思います。

**Comment by uttk** [comment]
了解です。

私もSquash and mergeで入れて行った方が良いと思っていたので、
Squash and mergeを使って行きましょう💪

ご意見ありがとうございました🙏
