### ISSUE TITLE
ページ全体の表記ゆれのチェック項目を策定する

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#67]
## 概要

全てのページの翻訳が完了した時に、全体を通して表記ゆれが無いかチェックする。
チェックする項目は、以下のチェックリストの内容を実施する。

## チェックリスト

- [ ] ひらがな書きが適切なモノが漢字で表記されている場合、ひらがな書きに直す( [参照](http://www.yamanouchi-yri.com/yrihp/techwrt-2-4s/t-2-4s03a.htm)  )
- [ ] `ひとつ, ふたつ, みっつ` など表現は、`一つ, 二つ, 三つ` のような漢数字を用いて表現する
- [ ] `return value` の翻訳は `返り値`  とする ( `戻り値` となっている所は、`返り値`に修正する )
- [ ] リンクとの間には半角スペースを入れる( 中国語翻訳と同じようにする )

随時追記していきます🖊 
提案が有れば、お気軽にコメントして下さい💁‍♂️💁‍♀️

**Comment by shioyang** [comment]
return value(s)
- 返り値
- 戻り値

今のところ、わたしは `返り値` で訳していますが、どちらか決めて統一したいですね。

**Comment by uttk** [comment]
@shioyang 

>今のところ、わたしは `返り値` で訳していますが、どちらか決めて統一したいですね。
React 公式に合わせるのが無難そう。

一通り見た感じだと、React 公式ではどちらも使ってるッポイ感じがしますね。
まぁ、今回の翻訳では `返り値` に統一する事にしましょう。

提案ありがとうございます🙇‍♂️

**Comment by shioyang** [comment]
`基づく` は、ひらがなの方が読みやすいかなと思っています。
全体で統一されていればいいと思うのですが、どうしましょうか。

公用文では `基づく` なのかな。
- 基づく
- もとづく

**Comment by shioyang** [comment]
`parse` をどう訳すか
- 解析する
- パースする

React 公式では一応 `パース` としているところはありました。
Ref: https://ja.reactjs.org/docs/code-splitting.html#import
> Babel が動的インポート構文をパースできても変換してしまわないようにする必要があります。

**Comment by uttk** [comment]
@shioyang 

> `基づく` は、ひらがなの方が読みやすいかなと思っています。
> 全体で統一されていればいいと思うのですが、どうしましょうか。

私の周りで読めない人が何人かいたので、 `もとづく` としたいと思います。


> `parse` をどう訳すか

`parse` は、専門的な意味も含まれるため、カタカナにするべきだと思います。
なので、今後は `パースする` または `パース` と訳するようにしましょう💪

**Comment by uttk** [comment]
ある程度まとまったのでクローズ( 参照: #75  )
その他に提案がある場合は、別途Issueを立てるか、Reopenして下さい。
