### ISSUE TITLE
公式サイトへ統合できるか確認する

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#7]
元々[公式サイト](https://swr.vercel.app/)とは別のサイトを作って、そこに翻訳したページを載せるつもりだったけど、[公式サイト](https://swr.vercel.app/)に中国語の翻訳が既にあるので、この際日本語も一緒に載せてもらった方が良さそう。

なので、このリポジトリのフォーク元に統合できないかの確認を取る。

**Comment by shioyang** [comment]
お、welcome の返信もらえましたね！

**Comment by uttk** [comment]
@shioyang 

https://github.com/vercel/swr-site/issues/88

コメントありがとうございました🙏
確認が取れたので、クローズします。
