### ISSUE TITLE
README.md の Contributors に日本語訳の貢献者を追記する

### ISSUE THREAD

**Issue by uttk** [uttk/swr-site#96]
## 概要

README.md の Contributors に日本語訳の貢献者を追記する。
現状は以下のように追記する予定。

> - Japanese translation done by uttk ([@uttk](https://github.com/uttk)), Tomohiro (Tomo) SHIOYA ([@shioyang](https://github.com/shioyang))

**Comment by uttk** [comment]
@shioyang 

上記の内容で良いか、確認お願いします🙏

**Comment by shioyang** [comment]
@uttk ありがとうございます。括弧はなくて大丈夫です。

Tomohiro (Tomo) SHIOYA → Tomohiro SHIOYA
